line-length = 120

[lint]
select = [
    "ALL",
]

ignore = [
    #### modules
    "ANN", # flake8-annotations

    "D100",   # ignore missing docs
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D203",
    "D211",
    "D212",
    "D213",
    "T201",
    "S104",
    "S603",
    "S607",
    "BLE001",
    "TRY003",
    "PLR2004",
    "RUF012",
    "DTZ005",
    "EM101",
]
